api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "offer-discount"
type = "function"
uid = "4665f558-c521-e0e3-2a2f-eb058597cbac79e61a1b"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [extensions.input.variables]
  namespace = "$app"
  key = "offer_input"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/offer-discount.wasm"
  watch = [ "src/**/*.rs" ]
